import {
  Home,
  Users,
  Settings,
  LayoutDashboard,
  Activity,
  UserCog,
  UserCheck,
  Package,
  CreditCard,
  Store,
  BookOpen,
  ChefHat,
  ReceiptText,
} from "lucide-react";

export const sidebarMenu = [
  {
    label: "Dashboard",
    path: "/dashboard",
    icon: Home,
    module: "dashboard",
  },
  {
    label: "Outlets",
    path: "/outlet-management",
    icon: Store,
    module: "outlets",
  },
  {
    label: "Users",
    path: "/user-management",
    icon: Users,
    module: "users",
  },
  {
    label: "Employees",
    path: "/employee-management",
    icon: UserCheck,
    module: "employees",
  },
  {
    label: "Orders",
    path: "/orders",
    icon: ReceiptText,
    module: "orders",
  },
  {
    label: "Kitchen",
    path: "/kitchen",
    icon: ChefHat,
    module: "orders",
  },
  {
    label: "Menu",
    path: "/menu-management",
    icon: BookOpen,
    module: "menu",
  },
  {
    label: "Customers",
    path: "/customer-management",
    icon: Users,
    module: "customers",
  },
  {
    label: "Inventory",
    path: "/inventory-management",
    icon: Package,
    module: "inventory",
  },
  {
    label: "Payments",
    path: "/payment-management",
    icon: CreditCard,
    module: "payments",
  },
  {
    label: "Employee Payments",
    path: "/employee-payment-management",
    icon: CreditCard,
    module: "employeePayments",
  },
  {
    label: "Application Settings",
    path: "/app-settings",
    icon: Settings,
    module: "settings",
  },
  {
    label: "Activity Logs",
    path: "/activity-log-management",
    icon: Activity,
    module: "activityLog",
  },
];
