"""fix user fk ambiguity

Revision ID: 04f51b8bfea6
Revises: 8bf68bb00cb1
Create Date: 2025-12-14 01:17:13.442105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f51b8bfea6'
down_revision: Union[str, Sequence[str], None] = '8bf68bb00cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
