"""fix user fk ambiguity

Revision ID: 2a30ae22d8ee
Revises: e8ff49219504
Create Date: 2025-12-14 01:00:11.299864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a30ae22d8ee'
down_revision: Union[str, Sequence[str], None] = 'e8ff49219504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'departments', ['department_name'])
    op.create_unique_constraint(None, 'designations', ['designation_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'designations', type_='unique')
    op.drop_constraint(None, 'departments', type_='unique')
    # ### end Alembic commands ###
