"""add the order spine: menu, orders, KOT and GST invoice lines

Revision ID: 449c3bc7935b
Revises: d4e6a8c1f3b5
Create Date: 2026-09-19

Autogenerated, then corrected by hand. Three of the proposed operations would
have been wrong to apply:

1. **Twelve `add_column(..., nullable=False)` with no server default.** That
   fails outright on a table that already holds invoices. Each one carries a
   `server_default` here, dropped again afterwards so the application stays the
   thing that decides these values.

2. **`drop_constraint('refresh_tokens_jti_key')`.** A false positive:
   `RefreshToken.jti` is `unique=True`, but SQLAlchemy renders that as a unique
   index while the earlier migration created a unique constraint, so the
   constraint looks unexplained. Dropping it would remove the guarantee that
   makes refresh-token replay detectable.

3. **`drop_index('ix_outlets_is_deleted')`.** Created deliberately for list
   performance and not declared on the model, so autogenerate wants it gone.

Items 2 and 3 were model/schema drift; both are declared on their models now,
and `alembic check` in CI keeps them that way.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "449c3bc7935b"
down_revision: str | Sequence[str] | None = "d4e6a8c1f3b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Columns added to `customer_invoices`, each with the default an existing row
# should get. An invoice raised before this migration has no line items and no
# tax breakup, so zero is the honest value — not NULL, which would make every
# later SUM() silently skip it.
INVOICE_MONEY_COLUMNS = (
    "subtotal",
    "discount_amount",
    "service_charge",
    "taxable_amount",
    "cgst_amount",
    "sgst_amount",
    "tax_amount",
    "round_off",
)


def _audit_columns() -> list[sa.Column]:
    """The `Common` base's columns, spelled out once."""
    return [
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "created_by", sa.Integer(), nullable=True, comment="User ID who created this record"
        ),
        sa.Column(
            "updated_by",
            sa.Integer(),
            nullable=True,
            comment="User ID who last updated this record",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], deferrable=True, initially="DEFERRED"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], deferrable=True, initially="DEFERRED"),
    ]


def upgrade() -> None:
    op.create_table(
        "menu_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("outlet_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        *_audit_columns(),
        sa.ForeignKeyConstraint(["outlet_id"], ["outlets.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("outlet_id", "name", name="uq_menu_categories_outlet_name"),
    )
    op.create_index(op.f("ix_menu_categories_id"), "menu_categories", ["id"])
    op.create_index(op.f("ix_menu_categories_outlet_id"), "menu_categories", ["outlet_id"])
    op.create_index(
        "ix_menu_categories_outlet_deleted", "menu_categories", ["outlet_id", "is_deleted"]
    )

    op.create_table(
        "menu_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("outlet_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=False, server_default="5"),
        sa.Column("hsn_code", sa.String(length=12), nullable=True),
        sa.Column("is_veg", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("is_available", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("prep_minutes", sa.Integer(), nullable=True),
        *_audit_columns(),
        sa.ForeignKeyConstraint(["category_id"], ["menu_categories.id"]),
        sa.ForeignKeyConstraint(["outlet_id"], ["outlets.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("outlet_id", "name", name="uq_menu_items_outlet_name"),
    )
    op.create_index(op.f("ix_menu_items_id"), "menu_items", ["id"])
    op.create_index(op.f("ix_menu_items_outlet_id"), "menu_items", ["outlet_id"])
    op.create_index(op.f("ix_menu_items_category_id"), "menu_items", ["category_id"])
    op.create_index("ix_menu_items_outlet_deleted", "menu_items", ["outlet_id", "is_deleted"])
    op.create_index("ix_menu_items_category", "menu_items", ["category_id", "is_deleted"])

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("outlet_id", sa.Integer(), nullable=False),
        sa.Column("order_number", sa.String(length=24), nullable=False),
        sa.Column(
            "order_type",
            sa.Enum("dine-in", "takeaway", "delivery", name="order_type_enum"),
            nullable=False,
            server_default="dine-in",
        ),
        sa.Column(
            "status",
            sa.Enum("open", "confirmed", "served", "billed", "cancelled", name="order_status_enum"),
            nullable=False,
            server_default="open",
        ),
        sa.Column("table_id", sa.Integer(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("guest_count", sa.Integer(), nullable=True),
        sa.Column(
            "discount_amount", sa.Numeric(precision=10, scale=2), nullable=False, server_default="0"
        ),
        sa.Column(
            "service_charge_percent",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
            server_default="0",
        ),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column("cancel_reason", sa.String(length=255), nullable=True),
        sa.Column(
            "placed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        *_audit_columns(),
        sa.ForeignKeyConstraint(["customer_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["outlet_id"], ["outlets.id"]),
        sa.ForeignKeyConstraint(["table_id"], ["tables.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("outlet_id", "order_number", name="uq_orders_outlet_number"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"])
    op.create_index(op.f("ix_orders_outlet_id"), "orders", ["outlet_id"])
    op.create_index(op.f("ix_orders_table_id"), "orders", ["table_id"])
    op.create_index("ix_orders_outlet_deleted", "orders", ["outlet_id", "is_deleted"])
    op.create_index("ix_orders_outlet_status", "orders", ["outlet_id", "status", "is_deleted"])
    op.create_index("ix_orders_placed_at", "orders", ["outlet_id", "placed_at"])

    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=True),
        sa.Column("item_name", sa.String(length=120), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=False, server_default="5"),
        sa.Column("hsn_code", sa.String(length=12), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=10, scale=3), nullable=False, server_default="1"),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "fired", "ready", "served", "cancelled", name="order_item_status_enum"
            ),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column("void_reason", sa.String(length=255), nullable=True),
        sa.Column("fired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("served_at", sa.DateTime(timezone=True), nullable=True),
        *_audit_columns(),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"]),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_items_id"), "order_items", ["id"])
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"])
    op.create_index(op.f("ix_order_items_menu_item_id"), "order_items", ["menu_item_id"])
    op.create_index("ix_order_items_order", "order_items", ["order_id", "is_deleted"])
    op.create_index("ix_order_items_status", "order_items", ["status", "is_deleted"])

    op.create_table(
        "invoice_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=True),
        sa.Column("order_item_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=160), nullable=False),
        sa.Column("hsn_code", sa.String(length=12), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "discount_amount", sa.Numeric(precision=10, scale=2), nullable=False, server_default="0"
        ),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=False, server_default="0"),
        sa.Column("taxable_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "cgst_amount", sa.Numeric(precision=10, scale=2), nullable=False, server_default="0"
        ),
        sa.Column(
            "sgst_amount", sa.Numeric(precision=10, scale=2), nullable=False, server_default="0"
        ),
        sa.Column("line_total", sa.Numeric(precision=10, scale=2), nullable=False),
        *_audit_columns(),
        sa.ForeignKeyConstraint(["invoice_id"], ["customer_invoices.id"]),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"]),
        sa.ForeignKeyConstraint(["order_item_id"], ["order_items.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoice_lines_id"), "invoice_lines", ["id"])
    op.create_index(op.f("ix_invoice_lines_invoice_id"), "invoice_lines", ["invoice_id"])
    op.create_index("ix_invoice_lines_invoice", "invoice_lines", ["invoice_id", "is_deleted"])
    op.create_index("ix_invoice_lines_menu_item", "invoice_lines", ["menu_item_id"])

    op.add_column("customer_invoices", sa.Column("order_id", sa.Integer(), nullable=True))
    op.add_column(
        "customer_invoices", sa.Column("invoice_number", sa.String(length=32), nullable=True)
    )
    for column in INVOICE_MONEY_COLUMNS:
        op.add_column(
            "customer_invoices",
            sa.Column(column, sa.Numeric(precision=10, scale=2), nullable=False, server_default="0"),
        )
    op.add_column(
        "customer_invoices",
        sa.Column("is_void", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "customer_invoices", sa.Column("void_reason", sa.String(length=255), nullable=True)
    )

    # The defaults existed only to backfill. Leaving them in place would make
    # the database, rather than the service layer, decide what a bill's tax is
    # when nobody says — which is how a column drifts back into being writable.
    for column in INVOICE_MONEY_COLUMNS:
        op.alter_column("customer_invoices", column, server_default=None)
    op.alter_column("customer_invoices", "is_void", server_default=None)

    op.create_index("ix_customer_invoices_date", "customer_invoices", ["outlet_id", "invoice_date"])
    op.create_index(op.f("ix_customer_invoices_order_id"), "customer_invoices", ["order_id"])
    op.create_unique_constraint(
        "uq_customer_invoices_number", "customer_invoices", ["outlet_id", "invoice_number"]
    )
    op.create_foreign_key(
        "fk_customer_invoices_order_id", "customer_invoices", "orders", ["order_id"], ["id"]
    )


def downgrade() -> None:
    op.drop_constraint("fk_customer_invoices_order_id", "customer_invoices", type_="foreignkey")
    op.drop_constraint("uq_customer_invoices_number", "customer_invoices", type_="unique")
    op.drop_index(op.f("ix_customer_invoices_order_id"), table_name="customer_invoices")
    op.drop_index("ix_customer_invoices_date", table_name="customer_invoices")

    op.drop_column("customer_invoices", "void_reason")
    op.drop_column("customer_invoices", "is_void")
    for column in reversed(INVOICE_MONEY_COLUMNS):
        op.drop_column("customer_invoices", column)
    op.drop_column("customer_invoices", "invoice_number")
    op.drop_column("customer_invoices", "order_id")

    op.drop_index("ix_invoice_lines_menu_item", table_name="invoice_lines")
    op.drop_index("ix_invoice_lines_invoice", table_name="invoice_lines")
    op.drop_index(op.f("ix_invoice_lines_invoice_id"), table_name="invoice_lines")
    op.drop_index(op.f("ix_invoice_lines_id"), table_name="invoice_lines")
    op.drop_table("invoice_lines")

    op.drop_index("ix_order_items_status", table_name="order_items")
    op.drop_index("ix_order_items_order", table_name="order_items")
    op.drop_index(op.f("ix_order_items_menu_item_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_id"), table_name="order_items")
    op.drop_table("order_items")

    op.drop_index("ix_orders_placed_at", table_name="orders")
    op.drop_index("ix_orders_outlet_status", table_name="orders")
    op.drop_index("ix_orders_outlet_deleted", table_name="orders")
    op.drop_index(op.f("ix_orders_table_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_outlet_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")

    op.drop_index("ix_menu_items_category", table_name="menu_items")
    op.drop_index("ix_menu_items_outlet_deleted", table_name="menu_items")
    op.drop_index(op.f("ix_menu_items_category_id"), table_name="menu_items")
    op.drop_index(op.f("ix_menu_items_outlet_id"), table_name="menu_items")
    op.drop_index(op.f("ix_menu_items_id"), table_name="menu_items")
    op.drop_table("menu_items")

    op.drop_index("ix_menu_categories_outlet_deleted", table_name="menu_categories")
    op.drop_index(op.f("ix_menu_categories_outlet_id"), table_name="menu_categories")
    op.drop_index(op.f("ix_menu_categories_id"), table_name="menu_categories")
    op.drop_table("menu_categories")

    # The enum types outlive their tables in Postgres; dropping them is what
    # makes a re-upgrade work rather than failing on "type already exists".
    for enum_name in ("order_item_status_enum", "order_status_enum", "order_type_enum"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
