"""fix user fk ambiguity

Revision ID: 6f8505d2f4ce
Revises: 2a30ae22d8ee
Create Date: 2025-12-14 01:02:33.257283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f8505d2f4ce'
down_revision: Union[str, Sequence[str], None] = '2a30ae22d8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    # ### end Alembic commands ###
