"""fix user fk ambiguity

Revision ID: 71b1ec80e1d8
Revises: a8efd7e747ef
Create Date: 2025-12-14 01:19:21.352308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b1ec80e1d8'
down_revision: Union[str, Sequence[str], None] = 'a8efd7e747ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
