"""Add index to inventory_item

Revision ID: 72c5cb3d84e5
Revises: bc6b513bffac
Create Date: 2025-12-14 00:05:46.231938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c5cb3d84e5'
down_revision: Union[str, Sequence[str], None] = 'bc6b513bffac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_inventory_items_name'), 'inventory_items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_items_name'), table_name='inventory_items')
    # ### end Alembic commands ###
