"""fix user fk ambiguity

Revision ID: 8bf68bb00cb1
Revises: 6f8505d2f4ce
Create Date: 2025-12-14 01:04:29.036763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf68bb00cb1'
down_revision: Union[str, Sequence[str], None] = '6f8505d2f4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
