"""add created_by and updated_by

Revision ID: c069d0857c4f
Revises: 41562847d3f2
Create Date: 2025-12-27 19:00:03.648937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c069d0857c4f'
down_revision: Union[str, Sequence[str], None] = '41562847d3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('bookings', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'bookings', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'bookings', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('customer_feedback', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('customer_feedback', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'customer_feedback', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'customer_feedback', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('customer_invoices', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('customer_invoices', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'customer_invoices', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'customer_invoices', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('departments', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('departments', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'departments', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'departments', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('designations', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('designations', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'designations', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'designations', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('employee_attendance', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('employee_attendance', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'employee_attendance', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'employee_attendance', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('employee_details', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('employee_details', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'employee_details', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'employee_details', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('employee_documents', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('employee_documents', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'employee_documents', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'employee_documents', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('employee_performance', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('employee_performance', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'employee_performance', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'employee_performance', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('incentives', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('incentives', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'incentives', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'incentives', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('increment_history', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('increment_history', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'increment_history', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'increment_history', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('inventory_categories', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('inventory_categories', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'inventory_categories', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'inventory_categories', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('inventory_items', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('inventory_items', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'inventory_items', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'inventory_items', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('inventory_logs', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('inventory_logs', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'inventory_logs', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'inventory_logs', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('payments', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('payments', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'payments', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'payments', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('profit_loss', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('profit_loss', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'profit_loss', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'profit_loss', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('roles', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('roles', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'roles', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'roles', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('salary_payments', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('salary_payments', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'salary_payments', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'salary_payments', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('salary_structures', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('salary_structures', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'salary_structures', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'salary_structures', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('services', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('services', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'services', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'services', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('tables', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('tables', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'tables', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'tables', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # The matching upgrade lets Postgres name these foreign keys, so there is
    # no name to drop them by. Dropping the column takes its constraint with
    # it, which is why there is no drop_constraint here.
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('tables', 'updated_by')
    op.drop_column('tables', 'created_by')
    op.drop_column('services', 'updated_by')
    op.drop_column('services', 'created_by')
    op.drop_column('salary_structures', 'updated_by')
    op.drop_column('salary_structures', 'created_by')
    op.drop_column('salary_payments', 'updated_by')
    op.drop_column('salary_payments', 'created_by')
    op.drop_column('roles', 'updated_by')
    op.drop_column('roles', 'created_by')
    op.drop_column('profit_loss', 'updated_by')
    op.drop_column('profit_loss', 'created_by')
    op.drop_column('payments', 'updated_by')
    op.drop_column('payments', 'created_by')
    op.drop_column('inventory_logs', 'updated_by')
    op.drop_column('inventory_logs', 'created_by')
    op.drop_column('inventory_items', 'updated_by')
    op.drop_column('inventory_items', 'created_by')
    op.drop_column('inventory_categories', 'updated_by')
    op.drop_column('inventory_categories', 'created_by')
    op.drop_column('increment_history', 'updated_by')
    op.drop_column('increment_history', 'created_by')
    op.drop_column('incentives', 'updated_by')
    op.drop_column('incentives', 'created_by')
    op.drop_column('employee_performance', 'updated_by')
    op.drop_column('employee_performance', 'created_by')
    op.drop_column('employee_documents', 'updated_by')
    op.drop_column('employee_documents', 'created_by')
    op.drop_column('employee_details', 'updated_by')
    op.drop_column('employee_details', 'created_by')
    op.drop_column('employee_attendance', 'updated_by')
    op.drop_column('employee_attendance', 'created_by')
    op.drop_column('designations', 'updated_by')
    op.drop_column('designations', 'created_by')
    op.drop_column('departments', 'updated_by')
    op.drop_column('departments', 'created_by')
    op.drop_column('customer_invoices', 'updated_by')
    op.drop_column('customer_invoices', 'created_by')
    op.drop_column('customer_feedback', 'updated_by')
    op.drop_column('customer_feedback', 'created_by')
    op.drop_column('bookings', 'updated_by')
    op.drop_column('bookings', 'created_by')
    # ### end Alembic commands ###
