"""update table EmployeeDocuments

Revision ID: e282a49c3d36
Revises: 96e02c27a048
Create Date: 2026-02-04 22:33:39.352085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e282a49c3d36'
down_revision: Union[str, Sequence[str], None] = '96e02c27a048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_documents', sa.Column('filename', sa.String(length=255), nullable=True))
    op.add_column('employee_documents', sa.Column('original_name', sa.String(length=255), nullable=True))
    op.add_column('employee_documents', sa.Column('size', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_documents', 'size')
    op.drop_column('employee_documents', 'original_name')
    op.drop_column('employee_documents', 'filename')
    # ### end Alembic commands ###
